# Generated by Django 4.2.7 on 2023-11-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(blank=True, default='/media/users/Аватарка без фото.png', null=True, upload_to='media/users/', verbose_name='аватар'),
        ),
    ]
