# Generated by Django 4.2.7 on 2023-11-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        ('users', '0003_alter_user_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_subscriptions',
            field=models.ManyToManyField(blank=True, null=True, to='publications.publication', verbose_name='подписка на публикации'),
        ),
    ]
