# Generated by Django 4.2.7 on 2023-12-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        ('users', '0004_user_user_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_subscriptions',
            field=models.ManyToManyField(blank=True, to='publications.publication', verbose_name='подписка на публикации'),
        ),
    ]
