version: '3'
services:

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5436:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: sh -c "sleep 3 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    ports:
      - '8001:8000'
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data: