# Generated by Django 4.2.7 on 2023-11-30 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='заголовок публикации')),
                ('publication_text', models.TextField(blank=True, null=True, verbose_name='содержание публикации')),
                ('publication_photo', models.ImageField(blank=True, null=True, upload_to='publications/', verbose_name='заставка')),
                ('is_public', models.BooleanField(choices=[(True, 'Публичная'), (False, 'Приватная')], default=True, verbose_name='статус публикации')),
                ('publication_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена публикации')),
                ('publication_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
                'ordering': ('id',),
            },
        ),
    ]
