# Generated by Django 4.2.7 on 2023-12-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='заголовок публикации')),
                ('publication_text', models.TextField(blank=True, null=True, verbose_name='содержание публикации')),
                ('publication_photo', models.ImageField(blank=True, null=True, upload_to='publications/', verbose_name='заставка')),
                ('is_public', models.CharField(choices=[('Публичная', 'Публичная'), ('Приватная', 'Приватная')], default=True, max_length=10, verbose_name='статус публикации')),
                ('publication_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='цена публикации')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
                'ordering': ('id',),
            },
        ),
    ]
